const ActionTypes = {
    PRODUCTS_LOADING: "PRODUCTS_LOADING",
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    PRODUCTS_FAILED: "PRODUCTS_FAILED",
    
    LOAD_PRODUCTS: "LOAD_PRODUCTS",
    HANDLE_FILTER: "HANDLE_FILTER",
    UPDATE_FILTER: "UPDATE_FILTER",
    CLEAR_FILTERS: "CLEAR_FILTERS",
    
    ADD_PRODUCT: "ADD_PRODUCT",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
    AMOUNT_TOGGLE: "AMOUNT_TOGGLE",
    GET_TOTALS: "GET_TOTALS"
}

export default ActionTypes;