export const ActionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    SET_PRODUCTS: "SET_PRODUCTS",
    SELECT_PRODUCT: "SELECT_PRODUCT",
    REMOVE_PRODUCT: "REMOVE_PRODUCT",
    INCREMENT: 'INCREMENT',
    GET_TOTALS: 'GET_TOTALS',
    FILTER_PRODUCTS: 'FILTER_PRODUCTS',
    HANDLE_CHANGE : 'HANDLE_CHANGE',
}